### ISSUE TITLE
Error:Could not find net.alhazmy13.catcho:library:0.1.0-beta.

### ISSUE THREAD

**Issue by iAbdulaziz** [alhazmy13/Catcho#2]
السلام عليكم أخوي عبدالله،

أحاول أضيف المكتبة لمشروعي، لكن يطلع لي خطأ! (شوف الخطأ في الصورة تحت)

**ملاحظة: أستخدم ProGuard في المشروع.**

* صورة للخطأ:
[http://imgur.com/lwe9DDP](http://imgur.com/lwe9DDP)

**Comment by alhazmy13** [comment]
وعليكم السلام, مافي اي مشكلة عندي واحتمال ان المشكلة من الانترنت عندك او تاكد ان البروجكت ماهو في وضع الـ offline

**Comment by iAbdulaziz** [comment]
الإنترنت تمام عندي، وحدّثت جميع المكتبات عندي بدون مشاكل. أيضًا، الـ Offline work معطلة في الأندرويد ستوديو.
